// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DangerousSettings } from "./DangerousSettings";
import type { Proxy } from "./Proxy";

export type ClientConfig = { connectTimeout: number | null, maxRedirections: number | null, proxy: Proxy | null, danger: DangerousSettings | null, userAgent: string | null, };
