// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FetchResponse = {
  status: number
  statusText: string
  headers: Array<[string, string]>
  url: string
  rid: number
}