// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BasicAuth } from "./BasicAuth";

export type ProxyConfig = { url: string; basicAuth: BasicAuth | null; noProxy: string | null };
