// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UrlOrConfig } from "./UrlOrConfig";

export type Proxy = {
  all: UrlOrConfig | null;
  http: UrlOrConfig | null;
  https: UrlOrConfig | null;
};
