// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProxyConfig } from './ProxyConfig'

export type UrlOrConfig = string | ProxyConfig