"$schema" = "schemas/schema.json"
[default]
description = "Allows all fetch operations"
permissions = [
  "allow-fetch",
  "allow-fetch-cancel",
  "allow-fetch-send",
  "allow-fetch-read-body",
  "allow-fetch-cancel-body",
  "allow-prepare-requester",
  "allow-set-cookie",
  "allow-get-cookie",
  "allow-get-all-cookies",
  "allow-delete-cookie"
]