name: 构建和发布

on:
  push:
    branches: ['main']

permissions:
  contents: write
  id-token: write

jobs:
  build:
    if: ${{ github.event.head_commit && contains(github.event.head_commit.message, '[pub]') }}
    runs-on: ubuntu-latest
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 25
          registry-url: 'https://registry.npmjs.org'
          
      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Bun
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      # build
      - name: Change version
        id: set-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IS_DUR_RUN: true
        run: |
          OLD_VERSION="$(bun ./script/update-version.mts)"
          echo "old_version=$OLD_VERSION" >> "$GITHUB_OUTPUT"

      - name: Build
        run: |
          # cargo test
          bun run build

      #publish
      - name: Run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          npm publish
          cargo publish --allow-dirty --no-verify
          npm exec semantic-release